FROM ubuntu:jammy

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -q
RUN apt-get install -y ssh
RUN apt-get install -y make
RUN apt-get install -y vim
RUN apt-get install -y --no-install-recommends tzdata
RUN apt-get install -y sphinx
RUN apt-get install -y python3-pip
RUN pip3 install sphinx-math-dollar

