#!/usr/bin/env python
"""Generate a provisional EcoSIM parameter-list (with bounds) for Phase 0 sampling.

The curated seed carries *relationships*, not ranges. Morris sampling needs
per-parameter [lower, upper] bounds. This script produces a first, PROVISIONAL
bounds artifact so an EcoSIM Phase-0 ensemble can be designed:

  * parameters = the calibratable subset in the seed's ``parameters:`` block
    (32 params; discrete I*TYP switches are excluded by construction — they are
    documented only under mechanisms, never in ``parameters:``).
  * default value = read from the PFT input NetCDF, at the dominant PFT slot
    (index 0 by default; BioCON test1_ex1 is effectively single-active-PFT).
  * bounds = default ± 50% of |default| (a defensible screening range), clamped
    to [0, 1] for fraction-like parameters and to >= 0 for non-negative kinds.
    Zero-valued defaults get a flagged [0, 1] placeholder.

The output CSV is directly consumable by
``phases/phase0_design/create_parameter_sample.py::parse_param_list`` (name +
lower_bound/upper_bound columns).

**These bounds are PROVISIONAL** — anchored only to the default value, not to
literature or expert priors. Refine per parameter before a production ensemble.

Usage:
    python scripts/generate_ecosim_bounds.py \
        [--seed models/ecosim/curated_seed.yaml] \
        [--pft-file Offline/EcoSIM_sample_files/input/ds_input__pft_test__ex1.nc] \
        [--pft-index 0] [--frac 0.5] \
        [--out models/ecosim/reference_bounds/ecosim_biocon_param_list.csv]

Author: Jing Tao with Claude
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path

import yaml

# Categories whose parameters are fractions bounded to [0, 1].
_FRACTION_CATEGORIES = {"stoichiometry"}  # N:C / P:C ratios stay small & positive
# Parameter names known to be [0,1] fractions (protein/chlorophyll partitions, albedo, porosity, clumping).
_FRACTION_PARAMS = {"RUBP", "CHL", "ETMX", "PEPC", "CHL4", "ALBP", "PORT", "CFI", "FCO2"}
# Parameters that may legitimately be negative (do not clamp to >= 0).
_SIGNED_PARAMS = {"OSMO"}  # leaf osmotic potential at zero water potential (MPa, negative)


def _bounds(name: str, category: str, default: float, frac: float):
    """Provisional [lo, hi] from a default value."""
    if default is None:
        return (0.0, 1.0, True)  # flagged placeholder
    d = float(default)
    if d == 0.0:
        return (0.0, 1.0, True)  # flagged placeholder
    span = frac * abs(d)
    lo, hi = d - span, d + span
    is_fraction = name in _FRACTION_PARAMS or category in _FRACTION_CATEGORIES
    if is_fraction:
        lo, hi = max(0.0, lo), min(1.0, hi) if d <= 1.0 else hi
    elif name not in _SIGNED_PARAMS and d > 0:
        lo = max(0.0, lo)
    return (lo, hi, False)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--seed", default="models/ecosim/curated_seed.yaml")
    ap.add_argument("--pft-file", default="Offline/EcoSIM_sample_files/input/ds_input__pft_test__ex1.nc")
    ap.add_argument("--pft-index", type=int, default=0, help="PFT slot to read defaults from (0-based)")
    ap.add_argument("--frac", type=float, default=0.5, help="fractional half-width of the bound (default 0.5 = +/-50%%)")
    ap.add_argument("--out", default="models/ecosim/reference_bounds/ecosim_biocon_param_list.csv")
    args = ap.parse_args()

    import netCDF4 as nc

    seed = yaml.safe_load(open(args.seed))
    params = seed["parameters"]  # the calibratable subset
    ds = nc.Dataset(args.pft_file)

    rows, flagged = [], []
    for name, meta in sorted(params.items()):
        cat = meta.get("category", "other")
        default = None
        if name in ds.variables:
            arr = ds.variables[name][:]
            try:
                default = float(arr[args.pft_index]) if arr.ndim else float(arr)
            except (IndexError, TypeError):
                default = None
        lo, hi, flag = _bounds(name, cat, default, args.frac)
        if flag:
            flagged.append(name)
        rows.append({
            "name": name, "category": cat,
            "default": "" if default is None else f"{default:.6g}",
            "lower_bound": f"{lo:.6g}", "upper_bound": f"{hi:.6g}",
            "bound_source": "PLACEHOLDER" if flag else "default+/-%d%%" % int(args.frac * 100),
        })
    ds.close()

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", newline="") as f:
        f.write("# PROVISIONAL EcoSIM parameter list + bounds (default-anchored, +/-%d%%).\n" % int(args.frac * 100))
        f.write("# Generated by scripts/generate_ecosim_bounds.py. Refine ranges before a production ensemble.\n")
        f.write("# Consumable by phases/phase0_design/create_parameter_sample.py::parse_param_list.\n")
        w = csv.DictWriter(f, fieldnames=["name", "category", "default", "lower_bound", "upper_bound", "bound_source"])
        w.writeheader()
        w.writerows(rows)

    print(f"wrote {len(rows)} parameters -> {out}")
    if flagged:
        print(f"  {len(flagged)} PLACEHOLDER bounds (zero/absent default, need manual ranges): {flagged}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
