#!/usr/bin/env python3
"""Assert that every CLOSED experiment cycle has a cycle report.

`calibration-discipline` per-cycle item 7 requires a synthesis report at each cycle end, and
`write-report` builds on that: a ROUND report synthesizes the CYCLE reports, not the raw phase
logs again. **Nothing enforced either half.**

MEASURED, 2026-09-09, and it is why this exists. Cycles 14, 15 and 16 of `EcoSIM_Lusignan` R1b
were closed with no cycle report, the omission was written into the round summary as "recorded as
debt rather than written", and the round was closed on top of it. The round report then synthesized
raw phase logs, which is the exact anti-pattern `write-report` names. Nothing anywhere produced a
signal, because every OTHER Phase-6 requirement that cycle met has a checker behind it and this one
did not: `check_offline_log_evidence.py` warns when a figure EXISTS and is not embedded, and cannot
warn about a report that was never written. The PI found it by reading the round report.

WHAT MAKES THIS CHECK FAIL, named first (`feedback_a_check_that_cannot_fail`):

  * a `_phase6_refinement_r{RR}_c{EE}_` log exists for a case and no directory under that case's
    `reports/` names round RR cycle EE  ->  one WARN per missing cycle;
  * the report-name matcher extracts a cycle token from NOTHING anywhere, or no case has a single
    phase-6 log  ->  a LOUD anti-silent-pass error, because that is what a renamed convention
    looks like from in here and it would otherwise read as "all clean forever".

SEVERITY IS WARN, DELIBERATELY, AND IT IS NOT DATE-GATED. Six real gaps exist today, all in one
case that another effort owns (`EcoSIM_BioCON` R1 c00/c01/c02/c10 and R3 c00/c02), so erroring
would block their commits over history this branch does not own. Date-gating instead -- the pattern
the sibling checkers use -- would exempt every one of those six and leave a check that cannot fail
on the day it ships. A visible warning that names the specific missing cycles is worth more than
either.

THE MATCHER IS THE HARD PART, and it had two bugs before it had none. Cases name cycle reports
four different ways, all live in this repo today:

    EcoSIM_TeRaCON     20260905a_R1_c00_corner_ladder                 c00, zero-padded
    EcoSIM_BioCON      20260717b_R1_cycle3_seedC_factorial            cycle3, unpadded
    PFLOTRAN_miniLEO   20260901a_R1_c00_Cycle_Report_Birnessite       c00 plus the word Cycle
    EcoSIM_Lusignan    20260908a_R1b_cycle13_the_two_halves...        cycle13, round tag R1b

  BUG 1, and it is the dangerous one. Extracting the round with `\\bR(\\d+)[a-z]?\\b` matches
  NOTHING on `R1_cycle3`, because `_` is a word character so there is no word boundary between the
  `1` and the `_`. The round therefore came back None for every report in the repo.
  BUG 2 followed from it. With the round unknown, a permissive `(None, cycle)` fallback let ANY
  round's cycle N satisfy EVERY round's cycle N: `EcoSIM_BioCON`'s `R2_c00` report was silently
  answering for R1 c00. The first measurement reported 1 missing cycle; the correct one reports 6.
  A checker that under-reports is worse than no checker, because it is trusted.

Exit 0 always unless the anti-silent-pass guard trips (2). Warnings are printed and counted.

Usage:
    python3 tools/check_cycle_reports.py                    # every case
    python3 tools/check_cycle_reports.py use_cases/EcoSIM_Lusignan
    python3 tools/check_cycle_reports.py --strict           # missing cycles become errors

Author: Jing Tao with Claude on Perlmutter
"""
from __future__ import annotations

import argparse
import re
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

#: A cycle is CLOSED when its Phase-6 refinement log exists. That stem is machine-generated by
#: `PhaseLogger`, so it is the one side of this comparison with a guaranteed shape.
PHASE6 = re.compile(r"_phase6_refinement_r(\d+)_c(\d+)[_.]")

#: The round tag in a report folder name. `(?:^|[_-])` rather than `\b`: `_` is a word character,
#: so `\bR1\b` does not match `R1_cycle3`. The optional trailing letter is for `R1b`.
REPORT_ROUND = re.compile(r"(?:^|[_-])R(\d+)[a-z]?(?=[_-]|$)", re.IGNORECASE)

#: The cycle token, accepting every form in use: c0, c00, cycle0, cycle13.
REPORT_CYCLE = re.compile(r"(?:^|[_-])(?:c|cycle)(\d{1,2})(?=[_-]|$)", re.IGNORECASE)


def report_cycles(name: str) -> set[tuple[int | None, int]]:
    """-> {(round or None, cycle)} the report folder `name` can answer for."""
    m = REPORT_ROUND.search(name)
    rnd = int(m.group(1)) if m else None
    return {(rnd, int(c.group(1))) for c in REPORT_CYCLE.finditer(name)}


def closed_cycles(case: Path) -> dict[tuple[int, int], str]:
    """-> {(round, cycle): the phase-6 log stem that closed it}."""
    out: dict[tuple[int, int], str] = {}
    logs = case / "memory" / "logs"
    if not logs.is_dir():
        return out
    for f in sorted(logs.glob("*_phase6_refinement_*.md")):
        m = PHASE6.search(f.name)
        if m:
            out[(int(m.group(1)), int(m.group(2)))] = f.name
    return out


def audit(case: Path):
    """-> (missing, n_closed, n_report_dirs, n_tokens) for one case."""
    closed = closed_cycles(case)
    reports = case / "reports"
    dirs = sorted(p for p in reports.glob("*") if p.is_dir()) if reports.is_dir() else []
    have: set[tuple[int | None, int]] = set()
    for d in dirs:
        have |= report_cycles(d.name)
    # A report with NO round tag is treated as answering for that cycle in any round. That is
    # permissive on purpose: a single-round case may legitimately omit the tag, and a false WARN
    # is what gets a checker ignored. A report that DOES carry a tag must match the round.
    untagged = {c for (r, c) in have if r is None}
    missing = [(rr, ee, stem) for (rr, ee), stem in sorted(closed.items())
               if (rr, ee) not in have and ee not in untagged]
    return missing, len(closed), len(dirs), len(have)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("cases", nargs="*", type=Path,
                    help="case directories; default is every use_cases/<Case>/ with phase logs")
    ap.add_argument("--strict", action="store_true",
                    help="treat a missing cycle report as an ERROR rather than a warning")
    a = ap.parse_args(argv)

    cases = a.cases or sorted(p for p in (ROOT / "use_cases").glob("*")
                              if (p / "memory" / "logs").is_dir())
    cases = [c if c.is_absolute() else (ROOT / c) for c in cases]

    warnings, total_closed, total_tokens = [], 0, 0
    print(f"cycle-report coverage — {len(cases)} case(s) checked")
    for case in cases:
        missing, n_closed, n_dirs, n_tok = audit(case)
        total_closed += n_closed
        total_tokens += n_tok
        if not n_closed:
            continue
        mark = "✔" if not missing else " "
        print(f"  {mark} {case.name:<22} {n_closed:>3} closed cycle(s), {n_dirs:>3} report dir(s)"
              + (f", {len(missing)} MISSING" if missing else ""))
        for rr, ee, stem in missing:
            warnings.append(
                f"{case.name} round {rr} cycle {ee} was CLOSED (its Phase-6 log is `{stem}`) and no "
                f"directory under `{case.name}/reports/` names it. `calibration-discipline` item 7 "
                f"requires a report at each cycle end, and `write-report` builds the ROUND report by "
                f"synthesizing the CYCLE reports -- without this one, the round report has to "
                f"re-derive from raw phase logs.")

    # ---- anti-silent-pass guard (`feedback_exact_strings_are_contracts`) --------------------
    # Both halves of this check key on a NAMING CONVENTION that another tool writes. If either
    # convention moves, every comparison below stops matching and this checker reports clean
    # forever -- the failure mode it is least able to detect about itself. So assert that each
    # side found something, and say which one went blind.
    if cases and total_closed == 0:
        print("\n✘ ANTI-SILENT-PASS: no `_phase6_refinement_r{RR}_c{EE}_` log found in ANY case.\n"
              "  Either no cycle has ever closed, or PhaseLogger's stem changed and this checker\n"
              "  is now blind. Verify by hand before trusting a clean run.", file=sys.stderr)
        return 2
    if cases and total_closed and total_tokens == 0:
        print("\n✘ ANTI-SILENT-PASS: phase-6 logs exist but NO report directory anywhere yields a\n"
              "  cycle token. Either no case writes cycle reports at all, or the report folder\n"
              "  naming convention moved away from `<date><letter>_R<N>_c<NN>_<topic>` and the\n"
              "  matcher needs updating. Reporting clean here would be a false pass.",
              file=sys.stderr)
        return 2

    if not warnings:
        print("\n✔ every closed experiment cycle has a cycle report")
        return 0

    label = "ERROR" if a.strict else "warn "
    print()
    for w in warnings:
        print(f"  {label} {w}")
    print(f"\n{len(warnings)} cycle(s) closed with no report"
          + (" — ERRORS" if a.strict else " (warnings; not blocking)"))
    print("Fix per .claude/skills/write-report/SKILL.md, the CYCLE report section.")
    return 1 if a.strict else 0


if __name__ == "__main__":
    raise SystemExit(main())
